### ISSUE TITLE
Rasp: Volume sliders show "strange" values 

### ISSUE THREAD

**Issue by christianTF** [JiriSko/amixer-webui#1]
![alsa mixer](https://cloud.githubusercontent.com/assets/14220265/18895563/fe80aa08-851a-11e6-806b-4d1ba512e4bb.JPG)

On Raspberry 1 the mixer shows strange values like -4500% (right slider), or only 0 to 2 % (left slider).

The mute-Button is working, and also on the right slider if you come about 100%, it seems to do something (but not 0-100% in correct scale).

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
Python 2.7.9
Linux raspi 4.4.13+ #894 Mon Jun 13 12:43:26 BST 2016 armv6l GNU/Linux

**Comment by christianTF** [comment]
This seems to be an issue with wrong calculation:
The range conforms to the devices' limits:


# amixer cget numid=1
numid=1,iface=MIXER,name='PCM Playback Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=-10239,max=400,step=0
  : values=-367
  | dBscale-min=-102.39dB,step=0.01dB,mute=1

**Comment by christianTF** [comment]
Hello,

it's me again. It seems that ALSA (or amixer) has a bug and does not accept negative values with cset. Therefore, the volume control with Raspberry does not work, as the driver defines a negative minimum value.

**Comment by JiriSko** [comment]
Fixed in #2.
