### ISSUE TITLE
Missing a systemD start script

### ISSUE THREAD

**Issue by substring** [JiriSko/amixer-webui#16]
Hi !

Nice app you made! Nice layout even on a smartphone!

The Makefile will crash if /etc/init.d doesn't exist (old sysVinit). Most distros now use systemd now for service startup. I'll try to make a PR asap if you're interested.

**Comment by JiriSko** [comment]
Hi, thanks!

I'm definitely interested. :-)

**Comment by gearhead** [comment]
How about this:
`[Unit]
Description=Amixer-WebUI Service
After=audio.target

[Service]
WorkingDirectory=/usr/share/amixer-webui
ExecStart=/usr/bin/python /usr/share/amixer-webui/alsamixer_webui.py
ExecReload=/usr/bin/kill -HUP $MAINPID
KillMode=process
Restart=always
RestartSec=10
StartLimitInterval=30
StartLimitBurst=20

[Install]
WantedBy=multi-user.target
`
