### ISSUE TITLE
Support for alsaequal

### ISSUE THREAD

**Issue by xt660x** [JiriSko/amixer-webui#3]
Hello JiriSko,

What about support for **alsaequal** in your nice webui? ;)

All the best

**Comment by JiriSko** [comment]
Hi xt660x,

thanks for tip. I'll see what I can do. :)

**Comment by xt660x** [comment]
Ok now :)

I managed to get it work with alsaequal by replacing "amixer" with "amixer -D equal" in 57 and 59 lines.

Original:
```
        if Handler.card is None:
            return ["amixer"]
        else:
            return ["amixer", "-c", "%d" % Handler.card]
```

New:
```
            return ["amixer", "-D", "equal"]
        else:
            return ["amixer", "-D", "equal"]
```

Of course I had to install alsaequal first, in Ubuntu:

`sudo apt-get install libasound2-plugin-equal`

**Comment by JiriSko** [comment]
Yep, that's simplest workaround. But I think that equalizer should have different UI than volume control (at least 90° rotated controls). So I wrote server backend and now I need to write frontend.

**Comment by xt660x** [comment]
Good :)  Thanks for update :)

**Comment by JiriSko** [comment]
Can you please test it? :)
Branch: [dev-equalizer](https://github.com/JiriSko/amixer-webui/tree/dev-equalizer)

**Comment by xt660x** [comment]
Yes, thanks, I will :)

**Comment by xt660x** [comment]
Hmm... I see no changes on the main screen... I mean no new controls for equalizer etc...:
![screenshot-alsa mixer webui on mikhail-mate - mozilla firefox](https://cloud.githubusercontent.com/assets/23733617/20826107/cdfcb3b2-b892-11e6-9f64-8ee07f2686b3.png)

While I can see text output for eq controls on the /equalizer/ page:

![screenshot-mozilla firefox](https://cloud.githubusercontent.com/assets/23733617/20826169/3f928f1a-b893-11e6-805b-768dae30b060.png)

**Comment by xt660x** [comment]
And interesting. If I change

`equal = True`

in alsamixer-webui.py

... then restart alsamixer-webui.py

then reload the page in browser - I can see EQ controls. But after next page reload it comes back to standard mixer controls like Master Playback and others.

**Comment by JiriSko** [comment]
That's weird, you should see equalizer button like on the screenshot: ![screenshot](https://raw.githubusercontent.com/JiriSko/amixer-webui/dev-equalizer/screenshot.png)
Sorry for dumb question but do you really have latest code from [dev-equalizer](https://github.com/JiriSko/amixer-webui/tree/dev-equalizer) branch?

**Comment by xt660x** [comment]
Yep, I do :) Well, seems I do :) It also came to my mind :) So I tried it first by pulling it throgh git (git pull, git checkout dev-equalizer), second - by downloading zip directly from the webpage (https://github.com/JiriSko/amixer-webui/tree/dev-equalizer) and extracting it to separate folder etc. Same result :)

May it be possible that actually branch itself does not containg the latest code? Sorry for dumb question ;)

**Comment by xt660x** [comment]
Just in case:

$ python --version
Python 2.7.3

**Comment by JiriSko** [comment]
Can you check Network card in Developer tools if /equalizer/ is loading?
![screenshot 2016-12-02 10 02 30](https://cloud.githubusercontent.com/assets/997061/20828240/e09ab738-b876-11e6-8b4b-f39e8016374e.png)

**Comment by xt660x** [comment]
Yep:

![screenshot-alsa mixer webui on mikhail-mate - mozilla firefox-2](https://cloud.githubusercontent.com/assets/23733617/20828503/07569088-b8a2-11e6-9e3b-ce09d9318157.png)

**Comment by JiriSko** [comment]
I found it :) This bug appears when you've got only one sound card. I'll fix it soon.

**Comment by xt660x** [comment]
Good! :)))

**Comment by JiriSko** [comment]
Fixed. Check it now please. :)

**Comment by xt660x** [comment]
Web-version works, thank! :) What about Android app? ;) I installed v 0.2.2 and there is no button for EQ :(

![screenshot-alsa mixer webui on mikhail-mate - mozilla firefox-3](https://cloud.githubusercontent.com/assets/23733617/20830926/fad63c40-b8ac-11e6-95f9-98103c3ada06.png)

**Comment by JiriSko** [comment]
Good. Thanks for your help with debugging. I'll merge it into master and release. ;)
And regarding android app, I didn't implement it yet.

**Comment by xt660x** [comment]
Thanks! :)

**Comment by JiriSko** [comment]
Equalizer support also added in [android app v0.3.0](https://github.com/JiriSko/amixer-webui-android/releases/tag/v0.3.0). :)
