### ISSUE TITLE
WSGI Application

### ISSUE THREAD

**Issue by marmeladema** [JiriSko/amixer-webui#5]
I'm using your webui on daily basis and wonder if you would be interrested in a WSGI version of your application ?
I'm planning to do it for my needs anyway but should i stay close to your code or you are not interrested at all and you won't be merging this evolution anyway ?

Thanks in advance :-)

**Comment by JiriSko** [comment]
I'm open to this idea. :)

**Comment by marmeladema** [comment]
Done in #6 :)

**Comment by JiriSko** [comment]
Merged in [v0.3.0](https://github.com/JiriSko/amixer-webui/releases/tag/v0.3.0). :)
