### ISSUE TITLE
Corrected startup script

### ISSUE THREAD

**Issue by xt660x** [JiriSko/amixer-webui#7]
Corrected startup script a little bit, to be able to run under particular user...
[amixer-webui.zip](https://github.com/JiriSko/amixer-webui/files/644485/amixer-webui.zip)

**Comment by JiriSko** [comment]
I'll implement it in new 0.3 version. :)

**Comment by xt660x** [comment]
Sorry, added some missing quotes. BTW, I added cd to directory where main script is as running it from outside of working directory seems make it non-working.
[amixer-webui_1.zip](https://github.com/JiriSko/amixer-webui/files/645129/amixer-webui_1.zip)

**Comment by JiriSko** [comment]
Done in [v0.3.0](https://github.com/JiriSko/amixer-webui/releases/tag/v0.3.0). :)

**Comment by xt660x** [comment]
Thank, everything works like a charm! :)
